### ISSUE TITLE
supervisor couldn't start logmonitor

### ISSUE THREAD

**Issue by insanity-den** [jlesage/docker-baseimage#13]
Can't run container on armv7 arch, getting:

> $ docker run jlesage/baseimage:ubuntu-18.04-v3.0.0-pre.7 /init
...
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] could not load 'logmonitor.dep': command failed (126)

> $ docker version
 Client:
  Version:      18.03.1-ce
  API version:  1.37
  Go version:   go1.9.2
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:13:21 2018
  OS/Arch:      linux/arm
  Experimental: false
  Orchestrator: swarm
Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:46:45 2018
  OS/Arch:      linux/arm
  Experimental: false

**Comment by jlesage** [comment]
The current version of the baseimage does not support ARM.

The next version will be muti-arch.

**Comment by insanity-den** [comment]
It's sad, thanx for info
