### ISSUE TITLE
Add support for Alpine Linux 3.16; drop end-of-life branches

### ISSUE THREAD

**Issue by dpward** [jlesage/docker-baseimage#14]
The latest release of [Czkawka](https://github.com/qarmin/czkawka#readme) depends on Rust 1.60+, which is only available in Alpine Linux 3.16. (Older releases of Czkawka have been packaged with [jlesage/docker-czkawka](https://github.com/jlesage/docker-czkawka).)

Also please note that Alpine Linux 3.10, 3.11, and 3.12, which all have [configuration files](https://github.com/jlesage/docker-baseimage/tree/master/versions) in this repository, have now [reached end-of-life](https://alpinelinux.org/releases/).

Both comments above also apply to [jlesage/docker-baseimage-gui](https://github.com/jlesage/docker-baseimage-gui).

Thank you!

**Comment by jlesage** [comment]
This is done in version 3.0.0 of the image.  baseimage-gui will follow soon :)
