### ISSUE TITLE
s6-sync hangs when shutting down containers

### ISSUE THREAD

**Issue by frosty5689** [jlesage/docker-baseimage#6]
S6 calls sync() when containers shutdown, this sometimes causes the container to hang on unRAID. The latest version of S6 has the option to enable it (default to disabled now).

https://github.com/just-containers/s6-overlay/issues/244

I started experiencing this on unRAID when I'm doing parity checks and the such.

**Comment by jlesage** [comment]
S6 is no longer used in version 3.0.0.
